### ISSUE TITLE
Packetfence ifIndex unknown connection type: Wifi Web Auth 

### ISSUE THREAD

**Issue by ccarfaro** [griddb/griddb_nosql#43] opened 2018-12-03 19:18 UTC
using Ruckus Virtual SmartZone with pacjetfence 8 during authentication receive message on log.

Dec  2 23:11:39 packetfence packetfence_httpd.portal: httpd.portal(15328) INFO: [mac:84:89:ad:8d:fc:d6] switch port is (177.190.199.252) ifIndex unknown connection type: Wifi Web Auth (pf::enforcement::_vlan_reevaluation)

Dec  3 15:35:49 packetfence pfqueue: pfqueue(11316) ERROR: [mac:84:89:ad:8d:fc:d6] Failed to contact Ruckus for deauthentication: 500 Can't connect to 177.190.199.252:9443 (certificate verify failed) (pf::Switch::Ruckus::SmartZone::deauthenticateMacWebservices) @ #

**Comment by knonomura** [comment] 2018-12-05 23:42
Thank you for your access.

Your issue is opened in griddb/griddb_nosql repository,
but I guess the destination of the issue is incorrect.

**Comment by knonomura** [comment] 2018-12-10 23:38
I close this issue.

**Closed by knonomura** 2018-12-10 23:38 UTC
